export const dailyReportData = {
  id: "687f8f5d43ad85be8106a4ce",
  saleId: 56019099471941,
  quotationInfo: null,
  saleDate: "2025-07-22T13:17:17.957Z",
  currency: "BDT",
  customerInfo: {
    customerId: "6851119b84bd0e63175277c4",
    phone: "+8801311254681",
    email: "rahim@gmail.com",
    name: "Rahim",
    address: "12 new house",
  },
  lineItems: [
    {
      productId: "686cdfdbac83204a1187c587",
      name: "Mercedes-AMG C 63 Saloon – Performance Redefined",
      attributes: ["black"],
      quantity: 3,
      returnedQuantity: 0,
      unitPrice: 300,
      discount: {
        type: "FIXED",
        value: 50,
      },
      unit: {
        unitId: "6851126c84bd0e63175277c7",
        name: "Kg",
      },
      totalAmount: 900,
      totalDiscount: 150,
      totalAfterDiscount: 750,
    },
    {
      productId: "6851125884bd0e63175277c5",
      name: "Men's Stylish Blue Pen-Stripe Shirt (Multiple Sizes) | Latest Trendy Design | Premium China Import",
      attributes: ["yellow", "m"],
      quantity: 2,
      returnedQuantity: 0,
      unitPrice: 150,
      discount: {
        type: "FIXED",
        value: 50,
      },
      unit: {
        unitId: "6851126c84bd0e63175277c7",
        name: "Kg",
      },
      totalAmount: 300,
      totalDiscount: 100,
      totalAfterDiscount: 200,
    },
    {
      productId: "6860b6e22cc8cc3eadcea272",
      name: "MacBook Pro 16-inch (M4 Pro, 2024) - Ultimate Performance & Portability",
      attributes: ["green"],
      quantity: 4,
      returnedQuantity: 0,
      unitPrice: 550,
      discount: {
        type: "FIXED",
        value: 150,
      },
      unit: {
        unitId: "6851126c84bd0e63175277c7",
        name: "Kg",
      },
      totalAmount: 2200,
      totalDiscount: 600,
      totalAfterDiscount: 1600,
    },
    {
      productId: "6873590a82294701d9f1ba3f",
      name: "HydraGlow Ultra-Moisturizing Cream – Deep Hydration for 24 Hours",
      attributes: ["white"],
      quantity: 5,
      returnedQuantity: 0,
      unitPrice: 500,
      discount: {
        type: "FIXED",
        value: 100,
      },
      unit: {
        unitId: "6851126c84bd0e63175277c7",
        name: "Kg",
      },
      totalAmount: 2500,
      totalDiscount: 500,
      totalAfterDiscount: 2000,
    },
  ],
  payments: [
    {
      id: "e92b8b9f-3c8d-47db-99e0-5c64bed174d5",
      account: {
        id: "6860e4a32cc8cc3eadcea276",
        type: "BANK",
        accountName: "JOHN DOE",
      },
      amount: 8000,
      paidDate: "2025-07-22T13:17:17.957Z",
      txnId: null,
      installmentNumber: null,
      rewardPointsInfo: null,
    },
  ],
  subtotal: 4550,
  discount: {
    type: "PERCENT",
    value: 30,
  },
  totalAfterDiscount: 3185,
  vat: {
    percent: 10,
    amount: 318.5,
  },
  totalAfterVat: 3503.5,
  deliveryCost: 2000,
  laborCost: 3000,
  totalAmount: 8503.5,
  totalPaid: 8000,
  totalRemaining: 503.5,
  installmentConfig: null,
  installments: [],
  installmentStatus: null,
  installmentDocuments: [],
  cashTenders: [
    {
      receivedAmount: 8000,
      returnAmount: 0,
      timestamp: "2025-07-22T13:17:17.957Z",
    },
  ],
  paymentStatus: "PARTIALLY_PAID",
  note: null,
  saleBy: {
    id: "68510fc684bd0e63175277c3",
    name: "Admin",
  },
  store: {
    id: "68510fc684bd0e63175277c1",
    name: "Shumon Shop",
    logo: {
      lg: "storage/store-logo/36212973072453-lg.webp",
      md: "storage/store-logo/36212973072453-md.webp",
      sm: "storage/store-logo/36212973072453-sm.webp",
    },
    phone: "+8801725326327",
    email: "shumon@gmail.com",
    address: "Uttara, Dhaka",
  },
};

export const storeData = {
  id: 10015,
  staffId: "68510fc684bd0e63175277c3",
  isAdmin: true,
  name: "Admin",
  setting: {
    storeId: "68510fc684bd0e63175277c1",
    name: "Shumon Shop",
    category: "ECOMMERCE",
    location: {
      country: null,
      state: null,
      city: null,
      zipCode: null,
      address: "Uttara, Dhaka",
    },
    contact: {
      phone: "+8801725326327",
      email: "shumon@gmail.com",
      socialMedia: {},
    },
    localization: {
      language: null,
      dateFormat: null,
      timeFormat: null,
      timeZone: null,
      currency: null,
    },
    appearance: {
      logo: {
        lg: "storage/store-logo/36212973072453-lg.webp",
        md: "storage/store-logo/36212973072453-md.webp",
        sm: "storage/store-logo/36212973072453-sm.webp",
      },
      primaryColor: "#f3a70c",
    },
    misc: {
      startDate: null,
    },
    features: {},
    askPassword: {},
    invoice: {
      salePrintPopup: "POS",
      invoiceInfo: {
        name: "Shumon Shop",
        email: "shumon@gmail.com",
        phones: ["+8801725326327"],
        address: "Uttara, Dhaka",
        logo: {
          lg: "storage/store-logo/36212973072453-lg.webp",
          md: "storage/store-logo/36212973072453-md.webp",
          sm: "storage/store-logo/36212973072453-sm.webp",
        },
        note: null,
        a4Info: {
          showPaymentDetails: false,
          showLogo: true,
          showName: true,
          showBarcode: true,
          showQrCode: true,
          showProductImage: false,
          showProductDescription: false,
          showProductShortDescription: false,
          showProductSku: false,
          showShippingAddress: true,
          showSignatureFields: false,
          showInWordsTotalPrice: false,
          showInWordsDue: true,
        },
        posInfo: {
          showPaymentDetails: true,
          showLogo: true,
          showName: true,
          showBarcode: true,
          showQrCode: false,
          showProductSku: false,
          showInWordsTotalPrice: true,
          showInWordsDue: false,
        },
        quotationInfo: {
          showBrand: false,
          showDescription: false,
          showShortDescription: false,
        },
        saleSignatures: [
          {
            label: null,
            image: {},
          },
          {
            label: null,
            image: {},
          },
          {
            label: null,
            image: {},
          },
        ],
        quotationSignatures: [
          {
            label: null,
            image: {},
          },
          {
            label: null,
            image: {},
          },
          {
            label: null,
            image: {},
          },
        ],
        gaps: {
          header: null,
          footer: null,
        },
      },
      barcode: {
        size: "MM44x34",
        paperType: "POS",
      },
      packaging: {
        logo: {},
        size: "MM76x101",
        note: null,
        showStoreLogo: false,
        showStoreName: false,
        showStorePhone: false,
        showStoreEmail: false,
        showStoreAddress: false,
        showCustomerName: false,
        showCustomerPhone: false,
        showCustomerEmail: false,
        showCustomerAddress: false,
        showQrCode: false,
        showBarcode: false,
      },
      shareable: {
        logo: {},
        note: null,
      },
    },
    rewardPointSetting: {
      minimumInvoiceAmount: null,
      rewardablePoint: null,
      conversionRate: null,
      isRepeatable: false,
    },
  },
  actions: {
    STORE_UPDATE: "STORE_UPDATE",
    STAFF_INVITE: "STAFF_INVITE",
    STAFF_CANCEL_INVITATION: "STAFF_CANCEL_INVITATION",
    STAFF_VIEW: "STAFF_VIEW",
    STAFF_UPDATE: "STAFF_UPDATE",
    STAFF_REMOVE: "STAFF_REMOVE",
    STAFF_ROLE_UPDATE: "STAFF_ROLE_UPDATE",
    ROLE_CREATE: "ROLE_CREATE",
    ROLE_VIEW: "ROLE_VIEW",
    ROLE_UPDATE: "ROLE_UPDATE",
    ROLE_REMOVE: "ROLE_REMOVE",
    SUPPLIER_CREATE: "SUPPLIER_CREATE",
    SUPPLIER_VIEW: "SUPPLIER_VIEW",
    SUPPLIER_UPDATE: "SUPPLIER_UPDATE",
    SUPPLIER_REMOVE: "SUPPLIER_REMOVE",
    CUSTOMER_CREATE: "CUSTOMER_CREATE",
    CUSTOMER_VIEW: "CUSTOMER_VIEW",
    CUSTOMER_UPDATE: "CUSTOMER_UPDATE",
    CUSTOMER_REMOVE: "CUSTOMER_REMOVE",
    POS_SALE_CREATE: "POS_SALE_CREATE",
    POS_SALE_VIEW: "POS_SALE_VIEW",
    POS_SALE_UPDATE: "POS_SALE_UPDATE",
    PRODUCT_CREATE: "PRODUCT_CREATE",
    PRODUCT_VIEW: "PRODUCT_VIEW",
    PRODUCT_UPDATE: "PRODUCT_UPDATE",
    PRODUCT_REMOVE: "PRODUCT_REMOVE",
    PRODUCT_ARCHIVE: "PRODUCT_ARCHIVE",
    PRODUCT_RESTORE: "PRODUCT_RESTORE",
    PRODUCT_PUBLISH: "PRODUCT_PUBLISH",
    PRODUCT_UNPUBLISH: "PRODUCT_UNPUBLISH",
    PRODUCT_VARIANCE_CREATE: "PRODUCT_VARIANCE_CREATE",
    PRODUCT_VARIANCE_VIEW: "PRODUCT_VARIANCE_VIEW",
    PRODUCT_VARIANCE_UPDATE: "PRODUCT_VARIANCE_UPDATE",
    PRODUCT_VARIANCE_REMOVE: "PRODUCT_VARIANCE_REMOVE",
    REPORT_VIEW: "REPORT_VIEW",
    REPORT_DOWNLOAD: "REPORT_DOWNLOAD",
  },
};
